version: '3'
services:
  jenkins:
    container_name: jenkins
    #image: jenkins/jenkins
    build:
      context: jenkins_maven
    ports:
      - "8080:8080"
    #volumes:
    #  - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  #remote_host:
    #container_name: remote-host
    #build:
      #context: centos
    #networks:
      #- net
networks:
  net:
